const products = [
    {
        "type": "Kỹ năng sống - Phát triển cá nhân",
        "img1": "/img/product/Kỹ năng sống - Phát triển cá nhân/Chiến tranh tiền tệ 1.jpg",
        "img2": "/img/product/Kỹ năng sống - Phát triển cá nhân/Chiến tranh tiền tệ 2.jpg",
        "img3": "/img/product/Kỹ năng sống - Phát triển cá nhân/Chiến tranh tiền tệ 3.jpg",
        "code": "KNS01",
        "name": "Chiến tranh tiền tệ",
        "price": "200.000",
        "author": "Dale Carnegie",
        "publisher": "Văn Học",
        "describe": "Đắc nhân tâm của Dale Carnegie là quyển sách của mọi thời đại và một hiện tượng đáng kinh ngạc trong ngành xuất bản Hoa Kỳ. Chiếm vị trí số một trong danh mục sách bán chạy nhất và trở thành một sự kiện có một không hai trong lịch sử ngành xuất bản thế giới và được đánh giá là một quyển sách có tầm ảnh hưởng nhất mọi thời đại.",
        "quantity": "1000",
    },
    {
        "type": ,
        "img1": ,
        "img2": ,
        "img3": ,
        "code": ,
        "name": ,
        "price": ,
        "author": ,
        "publisher": ,
        "describe": ,
        "quantity": ,
    },
    {
        "type": ,
        "img1": ,
        "img2": ,
        "img3": ,
        "code": ,
        "name": ,
        "price": ,
        "author": ,
        "publisher": ,
        "describe": ,
        "quantity": ,
    },
    {
        "type": ,
        "img1": ,
        "img2": ,
        "img3": ,
        "code": ,
        "name": ,
        "price": ,
        "author": ,
        "publisher": ,
        "describe": ,
        "quantity": ,
    },
    {
        "type": ,
        "img1": ,
        "img2": ,
        "img3": ,
        "code": ,
        "name": ,
        "price": ,
        "author": ,
        "publisher": ,
        "describe": ,
        "quantity": ,
    },
    {
        "type": ,
        "img1": ,
        "img2": ,
        "img3": ,
        "code": ,
        "name": ,
        "price": ,
        "author": ,
        "publisher": ,
        "describe": ,
        "quantity": ,
    },




];
export default products;